version: '3.9'

services:
  mosquitto-init:
    image: eclipse-mosquitto:2.0
    command: >-
      sh -c "mosquitto_passwd -b -c /mosquitto/config/passwordfile $${MQTT_USERNAME} $${MQTT_PASSWORD}"
    volumes:
      - mosquitto_conf:/mosquitto/config
    env_file: .env

  mosquitto:
    image: eclipse-mosquitto:2.0
    depends_on:
      mosquitto-init:
        condition: service_completed_successfully
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      - mosquitto_conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/1883 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-09-01T00-00-00Z.fips
    command: server /data --console-address :${MINIO_CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio-setup:
    image: minio/mc:RELEASE.2024-09-01T00-00-00Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >-
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${MINIO_BUCKET} || true &&
      mc anonymous set none local/${MINIO_BUCKET} || true
      "
    env_file: .env

  consumer:
    build: ./consumer
    depends_on:
      mosquitto:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    environment:
      MQTT_BROKER_URL: mqtt://mosquitto:1883
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MINIO_END_POINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: 'false'
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION}
      CONSUMER_BATCH_MAX_MESSAGES: ${CONSUMER_BATCH_MAX_MESSAGES}
      CONSUMER_BATCH_MAX_INTERVAL_MS: ${CONSUMER_BATCH_MAX_INTERVAL_MS}
      CONSUMER_LOG_LEVEL: ${CONSUMER_LOG_LEVEL}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mosquitto_conf:
  mosquitto_data:
  minio_data:


